@host = https://localhost:7174
@id = fb4e5c2c-fad2-433b-a415-f1644af1c34f

PUT {{host}}/repositorio/{{id}}
Content-Type: application/json

{
    "name": "BuBerDinner",
    "description": "BuberDinner is...",
    "language": "C",
    "UpdatedDateTime": "2025-06-18T23:48:22+00:00",
    "owner": "Cesar Matsubayashi",
    "repositoryUrl": "https://github.com/cesar-matsubayashi/buber-dinner"
}